### ISSUE TITLE
Query Issue with AMG Timeout

### ISSUE THREAD

**Issue by cougarisme** [grafana/athena-datasource#114]
I tried basic query,  
SELECT
  datetime_utc,
  power
FROM
  power_data
WHERE
  $__dateFilter(datetime_utc)

Added data source is all correct and I can see columns and table name correctly.  I got fail like below
![image](https://user-images.githubusercontent.com/44814737/149201488-cac3c1d9-b7e7-44c2-9219-cc392be18b41.png)

**Comment by mhausenblas** [comment]
Context: this is in AMG, might be the same reason as in #99

**Comment by andresmgot** [comment]
Seems so, AMG has a timeout of 60 seconds as explained in #99. Can that be increased?

**Comment by mhausenblas** [comment]
I shall be looking into that with @robbierolin yes

**Comment by sunker** [comment]
Correct me if I'm wrong @robbierolin, but I believe the timeout in AMG has been increased now. Is this still an issue @cougarisme?

**Comment by iwysiu** [comment]
Hi @cougarisme ! Is this still an issue?

**Comment by sunker** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!

**Comment by sunker** [comment]
For reference, also see [this](https://github.com/grafana/grafana/discussions/45325) discussion.
