### ISSUE TITLE
Database selector in the query editor doesn't show options after clicking on it

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/athena-datasource#291]
**What happened**:

I noticed when updating e2e tests that the database selector doesn't show options unless it's opened, closed, and then opened again. Looks like it only happens in Grafana v10+. I didn't notice a problem with the Redshift datasource with uses the same ResourceSelector component.

https://github.com/grafana/athena-datasource/assets/19530599/64cb40fe-a9fc-4420-90bb-cc2556bc8ca9

**What you expected to happen**:

Here's how it was working when running in Grafana v9.4.7

https://github.com/grafana/athena-datasource/assets/19530599/3d2718fd-bd8b-4408-93d8-f0e377ee6e82

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Athena in Grafana v10+
2. Add a panel with an Athena DS and click the database selector
3. Click away from the database selector to close it
4. Click the database selector again and now the options should appear.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 10+
- Plugin version: 2.12.0

**Comment by nmarrs** [comment]
Upon closer review, it appears that this issue is impacting more than just the "database" selector but seems to be an issue for "region", "data source", "database", possibly "table". "column" seems to be the only selector that consistently works as expected

https://github.com/user-attachments/assets/54d555ac-af57-49a6-a607-1fa7fa1c595c

**Comment by nmarrs** [comment]
My best understanding of where this issue is that react state was being updated but because of the array reference was not being rewritten the component was not re-rendering. In the case of redshift it appears that the state is being updated + modified into a new object as part of the fetch which is probably why the query form component is being rerendered and options are showing up as expected.
