### ISSUE TITLE
We are restricted to selecting only "standard regions".

### ISSUE THREAD

**Issue by mitsu-nishi** [grafana/athena-datasource#330]
**What happened**:
We are unable to execute Athena queries using the "me-central-1" region within the "Amazon Athena" data source. We attempted to manually input "me-central-1" into the "Default Region" field in the data source settings, but this did not resolve the issue.

**What you expected to happen**:
When utilizing the "Amazon Athena" data source, we anticipate the ability to select non-standard regions, such as "me-central-1", from the "Region" dropdown menu within the Grafana interface. This would enable us to execute Athena queries within the UAE region.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure a data source using "Amazon Athena".
2. Click the "Region" dropdown menu and review the available regions.
3. "me-central-1" is absent from the list, preventing us from executing Athena queries within the UAE region.

![issue_20240610](https://github.com/grafana/athena-datasource/assets/171110685/b36c1ae9-b75b-4621-bee4-a67737ec85ea)

**Environment**:
- Grafana version: 10.2.3
- Plugin version: 2.11.1
- User OS & Browser: Windows & Google Chrome (125.0.6422.142)

**Comment by sarahzinger** [comment]
Hello @mitsu-nishi!

Thank you for reporting this issue to us. I see 3 bugs here: 
- one I think we should allow users to type in any region as a string if we're missing a region. We do this in other datasources and I think it works well. AWS is frequently updating new regions and we will always be a bit out of date. 
- We should add me-central-1 to our list of standard regions for athena (see [here](https://github.com/grafana/athena-datasource/blob/b0d237c35edc753d6c074d697085571f25c3e199/pkg/athena/api/api.go#L139)) 
- We should also add this region to our list of standard regions in the grafana-aws-sdk (whcih is used in our configuration settings) and ultimately pull the list for the query editor from this list so that we have once source of truth https://github.com/grafana/grafana-aws-sdk-react/blob/54fc2b4424d9a94961a2ccb6c4af9c38a0899541/src/regions.ts#L4

Will talk with the team about when we can prioritize working on this. Thanks again!

**Comment by mitsu-nishi** [comment]
Hello @sarahzinger
Thank you for your reply.

I would also like to request support for the following regions, as they are experiencing similar issues.

・ap-south-2
・ap-southeast-3
・ap-southeast-4
・ca-west-1
・eu-central-2
・eu-south-2
・il-central-1
・me-central-1

This would be helpful for future use cases.
Thank you for your consideration.

**Comment by iwysiu** [comment]
Released a new version with the new regions: https://github.com/grafana/athena-datasource/releases/tag/v2.17.1
